DEFAULT_TARGET_EXTENSIONS = [
    ".txt",
    ".py",
    ".js",
    ".html",
    ".css",
    ".md",
    ".json",
    ".xml",
    ".yaml",
    ".yml",
    ".sh",
    ".java",
    ".c",
    ".cpp",
    ".h",
    ".hpp",
    ".cs",
    ".go",
    ".rb",
    ".php",
    ".swift",
    ".kt",
    ".kts",
    ".rs",
    ".toml",
    ".ini",
    ".cfg",
    ".sql",
    ".r",
    ".pl",
    ".pm",
    ".lua",
    ".dart",
    ".ex",
    ".exs",
    ".scala",
    ".hs",
    ".elm",
    ".erl",
    ".clj",
    ".f",
    ".f90",
    ".f95",
    ".for",
]

# Default directories to ignore during traversal
DEFAULT_IGNORE_DIRS = [
    "node_modules",
    "__pycache__",
    "dist",
    "build",
    "target",
    "venv",
    "env",
    "bin",
    "obj",
    "out",
]  # .git is implicitly handled by hidden dir logic in file_operations

# Default specific files to ignore
DEFAULT_IGNORE_FILES = ["output.txt"]  # Avoid reading its own output

# Default file extensions to ignore for content inclusion (binary, logs, etc.)
DEFAULT_IGNORE_EXTENSIONS = [
    ".log",
    ".tmp",
    ".bak",
    ".swp",
    ".o",
    ".obj",
    ".class",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".jar",
    ".war",
    ".ear",
    ".zip",
    ".tar",
    ".gz",
    ".rar",
    ".7z",
    ".iso",
    ".img",
    ".dmg",
    ".pdf",
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".odt",
    ".ods",
    ".odp",
    ".epub",
    ".mobi",
    ".mp3",
    ".wav",
    ".ogg",
    ".mp4",
    ".avi",
    ".mkv",
    ".mov",
    ".flv",
    ".webm",
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".bmp",
    ".tiff",
    ".svg",
    ".ico",
    ".woff",
    ".woff2",
    ".eot",
    ".ttf",
    ".otf",
]

# Maximum file size for content inclusion (in MB)
MAX_FILE_SIZE_MB = 5
MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024

# These can be overridden if you re-introduce command-line arguments for them
# For now, they just use the defaults.
TARGET_EXTENSIONS = DEFAULT_TARGET_EXTENSIONS
IGNORE_DIRS = DEFAULT_IGNORE_DIRS
IGNORE_FILES = DEFAULT_IGNORE_FILES
IGNORE_EXTENSIONS = DEFAULT_IGNORE_EXTENSIONS
